name: 'Runtime variables'
description: 'Load runtime variables from PR body'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  override-major-version:
    description: 'Override major version'
  override-testsuite-branch:
    description: 'Override platform test suite branch'
  override-dashmate-branch:
    description: 'Override dashmate branch'
outputs:
  testsuite-branch:
    description: 'Platform test suite branch'
  dashmate-branch:
    description: 'Dashmate test suite branch'
  current-branch:
    description: 'Current branch name'

runs:
  using: 'node12'
  main: 'main.js'
